# Generated by Django 5.1.15 on 2026-09-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('altura_cm', models.DecimalField(decimal_places=2, help_text='Estatura en centímetros', max_digits=5)),
                ('deporte', models.CharField(default='Fútbol', max_length=100)),
                ('posicion_rol', models.CharField(default='Atleta', max_length=100)),
                ('dominancia', models.CharField(default='Derecho', max_length=50)),
                ('lesiones_previas', models.TextField(blank=True, default='Ninguna')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'db_table': 'atletas',
                'ordering': ['-creado_en'],
            },
        ),
    ]
