# Generated by Django 5.1.15 on 2026-09-24 21:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('altura_cm', models.DecimalField(decimal_places=2, help_text='Estatura en centímetros', max_digits=5)),
                ('deporte', models.CharField(default='Fútbol', max_length=100)),
                ('posicion_rol', models.CharField(default='Atleta', max_length=100)),
                ('dominancia', models.CharField(default='Derecho', max_length=50)),
                ('lesiones_previas', models.TextField(blank=True, default='Ninguna')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'db_table': 'atletas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ENTRENADOR', 'Entrenador'), ('ATLETA', 'Atleta')], default='ATLETA', help_text='Rol del usuario en la plataforma (Entrenador o Atleta)', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('altura_cm', models.DecimalField(decimal_places=2, help_text='Estatura en centímetros', max_digits=5)),
                ('deporte', models.CharField(default='Fútbol', help_text='Disciplina deportiva principal', max_length=100)),
                ('posicion', models.CharField(default='General', help_text='Posición de juego o especialidad biomecánica', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del atleta', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Cuenta de usuario asociada a este perfil', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_atleta', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Atleta',
                'verbose_name_plural': 'Perfiles de Atletas',
                'db_table': 'perfiles_atletas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de inicio de la sesión')),
                ('tipo_ejercicio', models.CharField(help_text='Tipo de ejercicio biomecánico (ej. Sentadilla, Sprint, Salto Vertical)', max_length=100)),
                ('angulo_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Ángulo articular máximo alcanzado durante el movimiento (°)', max_digits=5, null=True)),
                ('velocidad_media', models.DecimalField(blank=True, decimal_places=2, help_text='Velocidad media de ejecución estimada (m/s o °/s)', max_digits=6, null=True)),
                ('weaviate_vector_id', models.CharField(blank=True, help_text='Identificador único del vector embebido de la serie en Weaviate', max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(help_text='Atleta evaluado en la sesión', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core_app.perfilatleta')),
            ],
            options={
                'verbose_name': 'Sesión de Entrenamiento',
                'verbose_name_plural': 'Sesiones de Entrenamiento',
                'db_table': 'sesiones_entrenamiento',
                'ordering': ['-fecha'],
            },
        ),
    ]
